# Generated by Django 2.1.5 on 2019-01-24 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='erzezeuieuo', max_length=15)),
                ('for_user', models.PositiveIntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(default=django.utils.timezone.now)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Addresse email')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('telephone', models.CharField(blank=True, max_length=11, null=True)),
                ('adresse', models.CharField(blank=True, max_length=150, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.IntegerField(blank=True, null=True)),
                ('myuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MyUser')),
            ],
        ),
    ]
