# Generated by Django 2.2.1 on 2019-06-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuserprofile',
            name='token',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
