# Generated by Django 2.2.1 on 2019-06-21 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuserprofile_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuserprofile',
            name='token',
        ),
    ]
