# Generated by Django 2.2.4 on 2019-09-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_myuserprofile_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountsToken',
        ),
    ]
